### PR TITLE
Removal of Sphinxbase dependency and update Pocketsphinx to v5.0.3

### PR DESCRIPTION
**Pull request by matt1432**
This was originally supposed to just port the software to Nix, but I struggled to make it work at first because the dependencies are very old at this point.

So, I got rid of Sphinxbase because it is now deprecated, updated Pocketsphinx to v5.0.3 and fixed every breaking changes this update caused.

Also, since I only use Nix I can't test building the software in the normal way so there might be some problems there.

### CODE REVIEW

**Comment by shirshak55** [comment]
it gives error on macos arm m2. 

```
      clang: warning: optimization flag '-fexpensive-optimizations' is not supported [-Wignored-optimization-argument]
      gizmo/media/audiodec.cpp:62:2: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
              avcodec_close(m_codecCtx);
              ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been explicitly marked deprecated here
      attribute_deprecated
      ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      gizmo/media/audiodec.cpp:103:16: error: no member named 'channel_layout' in 'AVFrame'
                      if (m_frame->channel_layout == 0)
                          ~~~~~~~  ^
      gizmo/media/audiodec.cpp:104:13: error: no member named 'channel_layout' in 'AVFrame'
                              m_frame->channel_layout
                              ~~~~~~~  ^
      gizmo/media/audiodec.cpp:105:46: error: no member named 'channels' in 'AVFrame'
                                      = av_get_default_channel_layout(m_frame->channels);
                                                                      ~~~~~~~  ^
      gizmo/media/audiodec.cpp:117:2: warning: 'av_init_packet' is deprecated [-Wdeprecated-declarations]
              av_init_packet(&packet);
              ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavcodec/packet.h:652:1: note: 'av_init_packet' has been explicitly marked deprecated here
      attribute_deprecated
      ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      2 warnings and 3 errors generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      
      ```

**Comment by shirshak55** [comment]
Other error:

```
      gizmo/media/audiodec.cpp:62:2: warning: 'avcodec_close' is deprecated [-Wdeprecated-declarations]
              avcodec_close(m_codecCtx);
              ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavcodec/avcodec.h:2386:1: note: 'avcodec_close' has been explicitly marked deprecated here
      attribute_deprecated
      ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      gizmo/media/audiodec.cpp:103:16: error: no member named 'channel_layout' in 'AVFrame'
                      if (m_frame->channel_layout == 0)
                          ~~~~~~~  ^
      gizmo/media/audiodec.cpp:104:13: error: no member named 'channel_layout' in 'AVFrame'
                              m_frame->channel_layout
                              ~~~~~~~  ^
      gizmo/media/audiodec.cpp:105:46: error: no member named 'channels' in 'AVFrame'
                                      = av_get_default_channel_layout(m_frame->channels);
                                                                      ~~~~~~~  ^
      gizmo/media/audiodec.cpp:117:2: warning: 'av_init_packet' is deprecated [-Wdeprecated-declarations]
              av_init_packet(&packet);
              ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavcodec/packet.h:652:1: note: 'av_init_packet' has been explicitly marked deprecated here
      attribute_deprecated
      ^
      /opt/homebrew/Cellar/ffmpeg/7.0.2_1/include/libavutil/attributes.h:100:49: note: expanded from macro 'attribute_deprecated'
      #    define attribute_deprecated __attribute__((deprecated))
                                                      ^
      2 warnings and 3 errors generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]
      ```

**Comment by shirshak55** [comment]
Even if i supress warning I will just get this error:

no-deprecated-declarations
      gizmo/media/audiodec.cpp:103:16: error: no member named 'channel_layout' in 'AVFrame'
                      if (m_frame->channel_layout == 0)
                          ~~~~~~~  ^
      gizmo/media/audiodec.cpp:104:13: error: no member named 'channel_layout' in 'AVFrame'
                              m_frame->channel_layout
                              ~~~~~~~  ^
      gizmo/media/audiodec.cpp:105:46: error: no member named 'channels' in 'AVFrame'
                                      = av_get_default_channel_layout(m_frame->channels);
                                                                      ~~~~~~~  ^
      3 errors generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]

**Comment by sc0ty** [comment]
Thank you for your work, but regretfully I have to inform you I will no longer maintain this project. See #197 for more info.
Ofc you're free to fork it and work on your own.

**Comment by shirshak55** [comment]
No worries, thanks for the existing code. It would be great if u can
deprecate whole repo, but that is your decision.

**Comment by sc0ty** [comment]
What do you mean by deprecate whole repo? I just did that

**Comment by sambartik** [comment]
> What do you mean by deprecate whole repo? I just did that

You can archive a repo in settings to make it read only. Additionally, it will display a banner when viewing the repo saying so.

**Comment by sc0ty** [comment]
Didn't know about that. Looks like exactly what I need, thx

**Pull request closed without merging**
